service: include-external-npm-packages-with-yarn-workspaces

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'yarn'
    includeModules:
      forceInclude:
        - lodash

functions:
  first:
    handler: handler.hello
    events:
      - http:
          method: GET
          path: first
          integration: lambda
