service: serverless-webpack-typescript-example
package:
  individually: true
# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello
          integration: lambda
  goodbye:
    handler: src/handler2.goodbye
    events:
      - http:
          method: get
          path: goodbye
          integration: lambda
custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'yarn'
    includeModules: true
