version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    versioning-strategy: increase
    ignore:
      - dependency-name: husky
        versions:
          - ">= 5.0.0"
      # require node >= 12
      - dependency-name: lint-staged
        versions:
          - ">= 11.0.0"
      # require node >= 12
      - dependency-name: fs-extra
        versions:
          - ">= 10.0.0"
      # require node > 10
      - dependency-name: mocha
        versions:
          - ">= 9.0.0"
      # require node > 10
      - dependency-name: jest
        versions:
          - ">= 28.0.0"
