blank_issues_enabled: false
contact_links:
  - name: Help / Questions / Discussions
    url: https://github.com/esbuild-kit/esbuild-loader/discussions
    about: Use GitHub Discussions for anything else
