 language: csharp
 matrix:
  include:
  - os: linux
    dist: trusty # Ubuntu 14.04
    sudo: required
    dotnet: 2.1.403
    mono: none
  - os: osx
    osx_image: xcode8.3 # macOS 10.12
    dotnet: 2.1.403
    mono: none
 install:
   - ulimit -n 1024
   - dotnet restore 
 script:
   - ulimit -n 1024
   - dotnet build
   - dotnet test Test/Test.csproj